### ISSUE TITLE
Copy map for the new website

### ISSUE THREAD

**Issue by franzejr** [remotemeetup/remotemeetup.github.io#5]
The new website should have the same map as the old website had.

Here is the [old website folder](https://github.com/remotemeetup/remotemeetup.github.io/tree/master/old_site).

**Comment by dgurnani12** [comment]
Working on this now

**Comment by franzejr** [comment]
@dgurnani12 any update? The current version is on remotemeetup.github.io

**Comment by dgurnani12** [comment]
I ran into an emergency, I'll let you know when im done working on it

**Comment by franzejr** [comment]
Aah @dgurnani12 no problem!

**Comment by adityatandon007** [comment]
@franzejr can I pick this up

**Comment by adityatandon007** [comment]
@franzejr I have tested this but it should work. Let me in case it is not what you want
