### ISSUE TITLE
Copy links from old website

### ISSUE THREAD

**Issue by franzejr** [remotemeetup/remotemeetup.github.io#6]
We had some old links from the old website.

Here is the [old website folder](https://github.com/remotemeetup/remotemeetup.github.io/tree/master/old_site).

**Comment by buzzfizz** [comment]
Can you explain further the issue?

**Comment by franzejr** [comment]
This will be better explained when the initial layout @knewter is doing https://github.com/remotemeetup/remotemeetup.github.io/issues/4 will be done. Basically in the `old_site` we have some links and we need to have these links in the new website.
